### ISSUE TITLE
Update to new driver

### ISSUE THREAD

**Issue by Rewt0r** [iuscommunity-pkg/php56u-pecl-mongo#1]
There is a new driver available to support mongodb 3.2 https://docs.mongodb.org/ecosystem/drivers/php/

This one is now a legacy version

**Comment by carlwgeorge** [comment]
Thanks for bringing this to our attention @Rewt0r.  I don't think switching the driver in this package is the best course of action; it is different code, with a different versions.  The legacy driver is at version 1.6.12, and the new mongdb driver is at version 1.1.2, so we would have to use an epoch to work around that anyways.  It seems like the appropriate course of action will be to create a new php56u-pecl-mongodb package.  Would you mind opening a request on our [wishlist](https://github.com/iuscommunity/wishlist)?

**Comment by carlwgeorge** [comment]
As stated, we will consider php56u-pecl-mongodb as a new request, but we don't plan to change php56u-pecl-mongo.
